version: '3.7'

services:
  db:
    container_name: brainny_register_db
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
